on:
  pull_request:
  push:
    branches:
      - main

name: check

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0

  check-rust:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        year:
        - 2015
        - 2016
        - 2021
        - 2022
        - 2023
        - 2024
    steps:
      - uses: actions/checkout@v3
      - uses: pkgxdev/setup@v1
      - name: check
        run: pkgx +rustc^1.65 +cargo cargo check
        working-directory: ${{ matrix.year }}
        env:
          RUSTFLAGS: "-D warnings"
      - name: fmt
        run: pkgx +rustc^1.65 +cargo cargo fmt --all -- --check
        working-directory: ${{ matrix.year }}
      - name: clippy
        run: pkgx +rustc^1.65 +cargo cargo clippy --all-features
        working-directory: ${{ matrix.year }}
        env:
          RUSTFLAGS: "-D warnings"
  check-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pkgxdev/setup@v1
      - run: pkgx npm ci
        working-directory: "2020"
      - name: eslint
        run: pkgx npm run check
        working-directory: "2020"
