on:
  pull_request:
  push:
    branches:
      - main

name: check

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@1.1.0

  check-rust:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        year:
        - 2015
        - 2021
        - 2022
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
      - name: check
        run:
          cargo check
        working-directory: ${{ matrix.year }}
        env:
          RUSTFLAGS: "-D warnings"
      - name: fmt
        run:
          cargo fmt --all -- --check
        working-directory: ${{ matrix.year }}
      - name: clippy
        run:
          cargo clippy --all-features
        working-directory: ${{ matrix.year }}
        env:
          RUSTFLAGS: "-D warnings"
  check-javascript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: teaxyz/setup@v0
      - run: npm ci
        working-directory: "2020"
      - name: eslint
        run: npm run check
        working-directory: "2020"
