# on:
#   pull_request:
#   push:
#     branches:
#       - main

# name: test

# jobs:
#   test:
#     name: test
#     env:
#       RUSTFLAGS:
#         -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort -D warnings
#       RUSTDOCFLAGS: -Cpanic=abort
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         year:
#           - 2015
#           - 2016
#           - 2020
#           - 2021
#           - 2022
#           - 2023
#           - 2024
#     steps:
#       - uses: actions/checkout@v3
#       - uses: pkgxdev/setup@v1
#       - run: pkgx +rustc^1.65 +cargo +xc xc run-year ${{ matrix.year }}
